name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
jobs:
  Deploy-PR-Preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Get the branch name
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      # Output the branch name to the logs  
      - name: Branch name
        run: echo Branch was set to ${{ steps.extract_branch.outputs.branch }}
      # Installing Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      # Pull all environment information from Vercel
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      # Deploying to Vercel
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: vercel deploy -m githubCommitRef=${{ steps.extract_branch.outputs.branch }} -m githubDeployment="1" -m githubCommitRepo=${{ github.repository }} --token=${{ secrets.VERCEL_TOKEN }} >> vcurl.txt
      # The deployment URL has been written to vcurl.txt, reading it here so it's accessible later
      - name: Read Vercel Deployment URL
        id: readfile
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: vcurl.txt
      # Replacing slashes in the branch name (e.g. feature/branch --> feature-branch)
      - name: Run find-and-replace to remove slashes in branch names
        uses: mad9000/actions-find-and-replace-string@3
        id: findandreplace
        with:
          source: ${{ steps.extract_branch.outputs.branch }}
          find: '/'
          replace: '-'
      # RFC 1035 mandates a domain can have a maximum length of 63 characters
      # This includes everything in a *.vercel.app domain
      # The max. length of the branch name must be calculated manually
      - name: Truncate to the max length
        uses: bhowell2/github-substring-action@1.0.2
        id: truncation
        with:
          value: ${{ steps.findandreplace.outputs.value }}
          length_from_start: 34
      # Preparing the domain for an alias with a predefined schema
      # In this case: domain-prefix-BRANCHNAME-domain-suffix.vercel.app
      - name: Set Alias URL
        run: echo "ALIAS_URL=$(echo domain-prefix-${{ steps.truncation.outputs.substring }}-domain-suffix.vercel.app)" >> $GITHUB_ENV
      # Writing the alias url to a txt-file to read later
      - name: Update aliasurl.txt
        run: echo Preview URL - https://${ALIAS_URL} >> aliasurl.txt
      # Aliasing the domain
      - name: Aliasing the URL
        run: vercel alias set ${{ steps.readfile.outputs.content }} ${ALIAS_URL} --token=${{ secrets.VERCEL_TOKEN }} --scope=vercel-support
      # Comment the domain to the PR on GitHub
      - name: Comment the URL on the PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: output_url
          filePath: aliasurl.txt
